version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: "mongo-scrap"
    ports:
      - 27017:27017
  scrapping:
    build: .
    depends_on:
      - mongodb
    ports:
      - 3005:3005
    restart: always
    command: node index.js

volumes:
  mongodb:
